import type { Metadata } from "next";
import "./globals.css";
import Provider from "./Provider";
import Navbar from "./components/Navbar";
import BottomBar from "./components/BottomBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-br from-[#354f52] via-[#84a98c] to-[#354f52] min-h-screen font-mono">
        <Provider>
          <Navbar/>
          <div className="pt-16">
            {children}
          </div>
          <BottomBar/>
        </Provider>
      </body>
    </html>
  );
}
